---
name: Build container
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-container:
    name: Build containers
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [arch]
    steps:
      - uses: actions/checkout@v3
      - name: build container ${{ matrix.os }}
        id: build-container
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/onemorebyte/dev-container
          tags: ${{ matrix.os }}
          containerfiles: |
            ./Containerfile.${{ matrix.os }}

      - name: push to image repo
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-container.outputs.image }}
          tags: ${{ steps.build-container.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
